<?php

namespace App\Filament\Widgets;

use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Facades\Auth;

class EarningsOverview extends BaseWidget
{
	protected static bool $isLazy = false;
    protected function getStats(): array
    {
        return [
            Stat::make("Earnings", "$123")
	            ->description("All time earnings"),
	        Stat::make("Subscriptions", 10)
		        ->description("All time subscriptions"),
	        Stat::make("Memberships", 3),
        ];
    }

	public static function canView(): bool
	{
		return Auth::user()->hasRole("Super Admin"); // TODO: Change the autogenerated stub
	}
}
